# Generated by Django 2.2 on 2023-09-18 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter blog post content here', max_length=50000),
            preserve_default=False,
        ),
    ]
