# Generated by Django 2.2 on 2023-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_blogpost_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-blog_title']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='my_field_name',
            new_name='blog_title',
        ),
    ]
